### ISSUE TITLE
投稿詳細APIの実装

### ISSUE THREAD

**Issue by Shunkicreate** [givery-bootcamp/dena-2024-team8#3]
# backend
endpoint: GET /posts/:postId
parameters: なし
response: Postエンティティ
認証: 不要
ヒント
PostRepositoryではlistメソッドとgetメソッドは別に定義してください。
ただ、実装的にはlistメソッドをOptionalで指定のidで検索できるようにしてgetメソッドはそれを呼び出すだけとする方がシンプルになります。

**Comment by sotazum** [comment]
### 質問
- ここはなぜ再度書かなければいけないのか
 https://github.com/givery-bootcamp/dena-2024-team8/blob/e65f38544b0569e36714e03c93061f705a0b879d/backend/internal/repositories/hello_world_repository.go#L14-L19
