### ISSUE TITLE
投稿一覧画面の実装

### ISSUE THREAD

**Issue by kurikinton105** [givery-bootcamp/dena-2024-team8#5]
https://github.com/givery-bootcamp/training-app-2024/issues/7

frontend
ルーティング: /
画面サンプル
React-App

画面のどこかにメニューを配置して、クリックしたら「トップ（＝投稿一覧）」に遷移するようにしてください。
アクセスされたらAPIを呼び出して投稿一覧を表示させてください。表示順はAPIレスポンスの順で構いません。
APIの呼び出しはfetchでOKです。他に使い慣れたライブラリなどあればそれでもOKです。
投稿一覧には「タイトル」「ユーザー名」「更新日時」を表示させてください。
[投稿詳細画面](https://github.com/givery-bootcamp/training-app-2024/issues/3)の作成後は投稿のどこかをクリックしたら、投稿詳細に移動するようにしてください。
ヒント
redux使うの慣れてない人はAPIの非同期処理とStoreの連結に苦戦するかもしれません。createAsyncThunkをうまく使ってAPIの処理をextraReducersに繋いでみましょう。このあたりの処理はSPA作成の中でも重要な概念です、ここで理解しておけば他のライブラリでも同様のメンタルマップを利用できます。
https://redux-toolkit.js.org/api/createAsyncThunk

**Comment by nntto** [comment]
> 投稿一覧には「タイトル」「ユーザー名」「更新日時」を表示させてください。
ユーザー名が含まれていなさそう。

これは、バックエンドチームが構築したAPIにユーザー名が含まれていないからか、、、
